'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowLeft, Loader2, Building, User, FileText, Brain, Zap, Target, Layers, Video, Mic, Palette, CheckCircle } from 'lucide-react'
import { useAuth } from '@/contexts/NextAuthContext'
import { useDatabaseData } from '@/contexts/DatabaseDataContext'

interface AssessmentFormProps {
  onAssessmentGenerated: (data: any) => void
  onBack: () => void
}

export default function AssessmentForm({ onAssessmentGenerated, onBack }: AssessmentFormProps) {
  const { user } = useAuth()
  const { createAssessment } = useDatabaseData()
  const [step, setStep] = useState<'type' | 'form'>('type')
  const [assessmentType, setAssessmentType] = useState<'traditional' | 'ai-powered'>('traditional')
  const [formData, setFormData] = useState({
    jobTitle: '',
    company: '',
    jobDescription: '',
    // AI-powered specific options
    useCreativeQuestions: false,
    useSelfModifying: false,
    useMultiModal: false,
    modalType: 'video' as 'video' | 'audio' | 'both',
    videoInstructions: '',
    audioInstructions: '',
    creativeType: 'scenario-based' as 'scenario-based' | 'case-study' | 'design-challenge',
    scenario: '',
    // Revolutionary live simulation options
    useLiveSimulation: false,
    simulationComplexity: 'advanced' as 'intermediate' | 'advanced' | 'expert',
    enablePlotTwists: false,
    enableRealTimeMetrics: false,
    enableAdaptiveDifficulty: false
  })
  const [isGenerating, setIsGenerating] = useState(false)

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const target = e.target as HTMLInputElement
    const { name, value, type, checked } = target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
  }

  const handleTypeSelection = (type: 'traditional' | 'ai-powered') => {
    setAssessmentType(type)
    setStep('form')
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsGenerating(true)

    try {
      let assessmentData = null
      let finalAssessmentType: 'traditional' | 'ai-powered' = 'traditional'
      
      // Use AI generation API for both traditional and AI-powered assessments
      if (formData.jobTitle && formData.company && formData.jobDescription) {
        console.log('🤖 Generating revolutionary AI assessment...')
        
        const response = await fetch('/api/generate-assessment', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            jobTitle: formData.jobTitle,
            company: formData.company,
            jobDescription: formData.jobDescription
          })
        })

        if (response.ok) {
          const aiAssessment = await response.json()
          assessmentData = aiAssessment // Use FULL revolutionary assessment data
          finalAssessmentType = 'ai-powered' // Mark as AI-powered since it was generated by AI
          console.log('✅ Revolutionary AI assessment generated:', aiAssessment.title || 'Untitled')
          console.log('🎮 Assessment type:', aiAssessment.assessmentType)
          console.log('🎯 Scenarios:', aiAssessment.scenarios?.length || 0)
          console.log('🎪 Unique features:', aiAssessment.uniqueFeatures?.length || 0)
        } else {
          console.error('❌ AI generation failed, falling back to mock assessment')
          const mockAssessment = generateMockAssessment()
          assessmentData = mockAssessment
          finalAssessmentType = assessmentType // Keep original selection
        }
      } else {
        console.log('📝 Using mock assessment (missing job details)')
        const mockAssessment = generateMockAssessment()
        assessmentData = mockAssessment
        finalAssessmentType = assessmentType // Keep original selection
      }
      
      const newAssessment = {
        // Use the revolutionary assessment data or fallback structure
        title: assessmentData.title || formData.jobTitle,
        company: assessmentData.company || formData.company,
        description: assessmentData.description || formData.jobDescription,
        questions: assessmentData.questions || [],
        duration: assessmentData.timeLimit || assessmentData.totalTime || (finalAssessmentType === 'traditional' ? 60 : 90),
        type: finalAssessmentType,
        
        // Revolutionary assessment fields (preserve ALL AI data)
        ...(assessmentData.assessmentType && {
          assessmentType: assessmentData.assessmentType,
          revolutionaryTitle: assessmentData.title,
          scenarios: assessmentData.scenarios,
          instructions: assessmentData.instructions,
          totalTime: assessmentData.totalTime,
          aiAssistanceMode: assessmentData.aiAssistanceMode,
          uniqueFeatures: assessmentData.uniqueFeatures,
          criteria: assessmentData.criteria
        }),
        
        // AI-powered specific fields from form
        ...(finalAssessmentType === 'ai-powered' && {
          creativeType: formData.useCreativeQuestions ? formData.creativeType : undefined,
          scenario: formData.useCreativeQuestions ? formData.scenario : undefined,
          selfModifying: formData.useSelfModifying,
          modalType: formData.useMultiModal ? formData.modalType : undefined,
          videoInstructions: formData.useMultiModal && (formData.modalType === 'video' || formData.modalType === 'both') ? formData.videoInstructions : undefined,
          audioInstructions: formData.useMultiModal && (formData.modalType === 'audio' || formData.modalType === 'both') ? formData.audioInstructions : undefined
        })
      }

      await createAssessment(newAssessment)
      
      // Pass the FULL revolutionary assessment data to the callback
      onAssessmentGenerated({ 
        ...newAssessment,
        // Ensure all revolutionary fields are preserved
        ...(assessmentData && {
          jobTitle: assessmentData.jobTitle,
          timeLimit: assessmentData.timeLimit || assessmentData.totalTime,
          instructions: assessmentData.instructions,
          criteria: assessmentData.criteria,
          scenarios: assessmentData.scenarios,
          uniqueFeatures: assessmentData.uniqueFeatures,
          assessmentType: assessmentData.assessmentType,
          aiAssistanceMode: assessmentData.aiAssistanceMode
        }),
        aiGenerated: finalAssessmentType === 'ai-powered'
      })
    } catch (error) {
      console.error('Error generating assessment:', error)
    } finally {
      setIsGenerating(false)
    }
  }

  const generateMockAssessment = () => {
    const baseQuestions = [
      {
        type: 'technical',
        question: `Explain the concept of ${formData.jobTitle.includes('Developer') ? 'closures in JavaScript' : 'data structures'} and provide a practical example.`,
        expectedAnswer: 'Technical explanation...',
        difficulty: 'Medium',
        category: 'Technical Knowledge'
      },
      {
        type: 'problem-solving',
        question: `How would you approach solving a complex ${formData.jobTitle.toLowerCase()} challenge with limited resources?`,
        expectedAnswer: 'Problem-solving approach...',
        difficulty: 'Hard',
        category: 'Problem Solving'
      }
    ]

    if (assessmentType === 'ai-powered') {
      // Add advanced questions based on selected options
      if (formData.useCreativeQuestions) {
        baseQuestions.push({
          type: 'creative',
          question: `Design a creative solution for: ${formData.scenario || 'improving user experience'}`,
          expectedAnswer: 'Creative solution...',
          difficulty: 'Medium',
          category: 'Creativity'
        })
      }
      if (formData.useSelfModifying) {
        baseQuestions.push({
          type: 'adaptive',
          question: 'This question will adapt based on your previous answers...',
          expectedAnswer: 'Adaptive response...',
          difficulty: 'Variable',
          category: 'Adaptive Assessment'
        })
      }
      if (formData.useMultiModal) {
        baseQuestions.push({
          type: 'multimodal',
          question: `Record a ${formData.modalType} response explaining your approach to ${formData.jobTitle.toLowerCase()} challenges`,
          expectedAnswer: 'Multimodal response...',
          difficulty: 'Medium',
          category: 'Communication'
        })
      }
    }

    return {
      jobTitle: formData.jobTitle,
      company: formData.company,
      questions: baseQuestions,
      timeLimit: assessmentType === 'traditional' ? 45 : 75,
      type: assessmentType
    }
  }

  if (step === 'type') {
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-gray-800 rounded-xl shadow-2xl p-8"
        >
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-white mb-4">Choose Assessment Type</h1>
            <p className="text-gray-300">Select the type of assessment you want to create</p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {/* Traditional Assessment */}
            <motion.div
              whileHover={{ scale: 1.02 }}
              className="bg-gray-700 rounded-xl p-6 border-2 border-transparent hover:border-blue-500 cursor-pointer transition-all duration-300"
              onClick={() => handleTypeSelection('traditional')}
            >
              <div className="text-center">
                <div className="w-16 h-16 bg-blue-500 rounded-full flex items-center justify-center mx-auto mb-4">
                  <FileText className="w-8 h-8 text-white" />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">Traditional Assessment</h3>
                <p className="text-gray-300 mb-4">
                  Standard assessment format with pre-defined questions and straightforward evaluation.
                </p>
                <div className="space-y-2 text-sm text-gray-400">
                  <div className="flex items-center justify-center">
                    <CheckCircle className="w-4 h-4 mr-2 text-green-400" />
                    <span>Quick setup</span>
                  </div>
                  <div className="flex items-center justify-center">
                    <CheckCircle className="w-4 h-4 mr-2 text-green-400" />
                    <span>Standard questions</span>
                  </div>
                  <div className="flex items-center justify-center">
                    <CheckCircle className="w-4 h-4 mr-2 text-green-400" />
                    <span>45 minutes duration</span>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* AI-Powered Assessment */}
            <motion.div
              whileHover={{ scale: 1.02 }}
              className="bg-gray-700 rounded-xl p-6 border-2 border-transparent hover:border-purple-500 cursor-pointer transition-all duration-300 relative overflow-hidden"
              onClick={() => handleTypeSelection('ai-powered')}
            >
              <div className="absolute top-2 right-2">
                <span className="bg-purple-500 text-white text-xs px-2 py-1 rounded-full">AI-Powered</span>
              </div>
              <div className="text-center">
                <div className="w-16 h-16 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Brain className="w-8 h-8 text-white" />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">AI-Powered Assessment</h3>
                <p className="text-gray-300 mb-4">
                  Advanced assessment with AI-driven features including creative questions, adaptive testing, and multimodal responses.
                </p>
                <div className="space-y-2 text-sm text-gray-400">
                  <div className="flex items-center justify-center">
                    <Palette className="w-4 h-4 mr-2 text-purple-400" />
                    <span>Creative questions</span>
                  </div>
                  <div className="flex items-center justify-center">
                    <Zap className="w-4 h-4 mr-2 text-purple-400" />
                    <span>Self-modifying</span>
                  </div>
                  <div className="flex items-center justify-center">
                    <Video className="w-4 h-4 mr-2 text-purple-400" />
                    <span>Video/Audio responses</span>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>

          <div className="mt-8 text-center">
            <button
              onClick={onBack}
              className="inline-flex items-center space-x-2 text-gray-400 hover:text-gray-300 transition-colors"
            >
              <ArrowLeft className="h-4 w-4" />
              <span>Back to Assessments</span>
            </button>
          </div>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-gray-800 rounded-xl shadow-2xl p-8"
      >
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-white mb-2">
              Create {assessmentType === 'traditional' ? 'Traditional' : 'AI-Powered'} Assessment
            </h1>
            <p className="text-gray-300">
              {assessmentType === 'traditional' 
                ? 'Generate a standard assessment with pre-defined questions'
                : 'Create an advanced AI-powered assessment with custom features'
              }
            </p>
          </div>
          <button
            onClick={() => setStep('type')}
            className="text-blue-400 hover:text-blue-300 transition-colors"
          >
            Change Type
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <div className="grid md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Job Title *
              </label>
              <div className="relative">
                <User className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
                <input
                  type="text"
                  name="jobTitle"
                  value={formData.jobTitle}
                  onChange={handleInputChange}
                  className="w-full pl-10 pr-4 py-3 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-white placeholder-gray-400"
                  placeholder="e.g., Frontend Developer"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-2">
                Company *
              </label>
              <div className="relative">
                <Building className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
                <input
                  type="text"
                  name="company"
                  value={formData.company}
                  onChange={handleInputChange}
                  className="w-full pl-10 pr-4 py-3 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-white placeholder-gray-400"
                  placeholder="e.g., Tech Corp"
                  required
                />
              </div>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Job Description *
            </label>
            <textarea
              name="jobDescription"
              value={formData.jobDescription}
              onChange={handleInputChange}
              rows={4}
              className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-white placeholder-gray-400"
              placeholder="Describe the role, responsibilities, and requirements..."
              required
            />
          </div>

          {/* AI-Powered Specific Options */}
          {assessmentType === 'ai-powered' && (
            <div className="bg-gray-700 rounded-lg p-6 space-y-6">
              <h3 className="text-lg font-semibold text-white mb-4">AI-Powered Features</h3>
              
              {/* Creative Questions */}
              <div className="flex items-start space-x-3">
                <input
                  type="checkbox"
                  id="useCreativeQuestions"
                  name="useCreativeQuestions"
                  checked={formData.useCreativeQuestions}
                  onChange={handleInputChange}
                  className="mt-1 rounded border-gray-600 bg-gray-700 text-purple-500 focus:ring-purple-500"
                />
                <div className="flex-1">
                  <label htmlFor="useCreativeQuestions" className="text-white font-medium cursor-pointer">
                    Include Creative Questions
                  </label>
                  <p className="text-gray-400 text-sm">Add scenario-based and creative problem-solving questions</p>
                  
                  {formData.useCreativeQuestions && (
                    <div className="mt-4 space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">Creative Type</label>
                        <select
                          name="creativeType"
                          value={formData.creativeType}
                          onChange={handleInputChange}
                          className="w-full px-4 py-2 bg-gray-600 border border-gray-500 rounded-lg text-white"
                        >
                          <option value="scenario-based">Scenario-based</option>
                          <option value="case-study">Case Study</option>
                          <option value="design-challenge">Design Challenge</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">Scenario Description</label>
                        <textarea
                          name="scenario"
                          value={formData.scenario}
                          onChange={handleInputChange}
                          rows={2}
                          className="w-full px-4 py-2 bg-gray-600 border border-gray-500 rounded-lg text-white placeholder-gray-400"
                          placeholder="Describe the creative scenario or challenge..."
                        />
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Self-Modifying */}
              <div className="flex items-start space-x-3">
                <input
                  type="checkbox"
                  id="useSelfModifying"
                  name="useSelfModifying"
                  checked={formData.useSelfModifying}
                  onChange={handleInputChange}
                  className="mt-1 rounded border-gray-600 bg-gray-700 text-purple-500 focus:ring-purple-500"
                />
                <div>
                  <label htmlFor="useSelfModifying" className="text-white font-medium cursor-pointer">
                    Self-Modifying Assessment
                  </label>
                  <p className="text-gray-400 text-sm">Questions adapt based on candidate's previous answers</p>
                </div>
              </div>

              {/* Multi-Modal */}
              <div className="flex items-start space-x-3">
                <input
                  type="checkbox"
                  id="useMultiModal"
                  name="useMultiModal"
                  checked={formData.useMultiModal}
                  onChange={handleInputChange}
                  className="mt-1 rounded border-gray-600 bg-gray-700 text-purple-500 focus:ring-purple-500"
                />
                <div className="flex-1">
                  <label htmlFor="useMultiModal" className="text-white font-medium cursor-pointer">
                    Multi-Modal Responses
                  </label>
                  <p className="text-gray-400 text-sm">Allow video and audio responses</p>
                  
                  {formData.useMultiModal && (
                    <div className="mt-4 space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">Response Type</label>
                        <select
                          name="modalType"
                          value={formData.modalType}
                          onChange={handleInputChange}
                          className="w-full px-4 py-2 bg-gray-600 border border-gray-500 rounded-lg text-white"
                        >
                          <option value="video">Video Only</option>
                          <option value="audio">Audio Only</option>
                          <option value="both">Both Video & Audio</option>
                        </select>
                      </div>
                      {(formData.modalType === 'video' || formData.modalType === 'both') && (
                        <div>
                          <label className="block text-sm font-medium text-gray-300 mb-2">Video Instructions</label>
                          <textarea
                            name="videoInstructions"
                            value={formData.videoInstructions}
                            onChange={handleInputChange}
                            rows={2}
                            className="w-full px-4 py-2 bg-gray-600 border border-gray-500 rounded-lg text-white placeholder-gray-400"
                            placeholder="Instructions for video responses..."
                          />
                        </div>
                      )}
                      {(formData.modalType === 'audio' || formData.modalType === 'both') && (
                        <div>
                          <label className="block text-sm font-medium text-gray-300 mb-2">Audio Instructions</label>
                          <textarea
                            name="audioInstructions"
                            value={formData.audioInstructions}
                            onChange={handleInputChange}
                            rows={2}
                            className="w-full px-4 py-2 bg-gray-600 border border-gray-500 rounded-lg text-white placeholder-gray-400"
                            placeholder="Instructions for audio responses..."
                          />
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>

              {/* REVOLUTIONARY: Live Simulation */}
              <div className="flex items-start space-x-3">
                <input
                  type="checkbox"
                  id="useLiveSimulation"
                  name="useLiveSimulation"
                  checked={formData.useLiveSimulation || false}
                  onChange={handleInputChange}
                  className="mt-1 rounded border-gray-600 bg-gray-700 text-purple-500 focus:ring-purple-500"
                />
                <div className="flex-1">
                  <label htmlFor="useLiveSimulation" className="text-white font-medium cursor-pointer">
                    🚀 Live Interactive Simulation
                  </label>
                  <p className="text-gray-400 text-sm">Generate real, executable code environments with plot twists</p>
                  
                  {formData.useLiveSimulation && (
                    <div className="mt-4 space-y-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">Simulation Complexity</label>
                        <select
                          name="simulationComplexity"
                          value={formData.simulationComplexity || 'advanced'}
                          onChange={handleInputChange}
                          className="w-full px-4 py-2 bg-gray-600 border border-gray-500 rounded-lg text-white"
                        >
                          <option value="intermediate">Intermediate</option>
                          <option value="advanced">Advanced</option>
                          <option value="expert">Expert</option>
                        </select>
                      </div>
                      <div className="space-y-2">
                        <label className="text-sm font-medium text-gray-300">Revolutionary Features</label>
                        <div className="space-y-2">
                          <div className="flex items-center space-x-2">
                            <input
                              type="checkbox"
                              id="enablePlotTwists"
                              name="enablePlotTwists"
                              checked={formData.enablePlotTwists || false}
                              onChange={handleInputChange}
                              className="rounded border-gray-600 bg-gray-700 text-orange-500 focus:ring-orange-500"
                            />
                            <label htmlFor="enablePlotTwists" className="text-gray-300 text-sm">
                              Plot Twists & Complications
                            </label>
                          </div>
                          <div className="flex items-center space-x-2">
                            <input
                              type="checkbox"
                              id="enableRealTimeMetrics"
                              name="enableRealTimeMetrics"
                              checked={formData.enableRealTimeMetrics || false}
                              onChange={handleInputChange}
                              className="rounded border-gray-600 bg-gray-700 text-green-500 focus:ring-green-500"
                            />
                            <label htmlFor="enableRealTimeMetrics" className="text-gray-300 text-sm">
                              Real-Time Performance Metrics
                            </label>
                          </div>
                          <div className="flex items-center space-x-2">
                            <input
                              type="checkbox"
                              id="enableAdaptiveDifficulty"
                              name="enableAdaptiveDifficulty"
                              checked={formData.enableAdaptiveDifficulty || false}
                              onChange={handleInputChange}
                              className="rounded border-gray-600 bg-gray-700 text-blue-500 focus:ring-blue-500"
                            />
                            <label htmlFor="enableAdaptiveDifficulty" className="text-gray-300 text-sm">
                              Adaptive Difficulty Based on Performance
                            </label>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          <div className="flex justify-between items-center pt-6">
            <button
              type="button"
              onClick={() => setStep('type')}
              className="inline-flex items-center space-x-2 text-gray-400 hover:text-gray-300 transition-colors"
            >
              <ArrowLeft className="h-4 w-4" />
              <span>Back to Type Selection</span>
            </button>

            <button
              type="submit"
              disabled={isGenerating}
              className="inline-flex items-center space-x-2 bg-gradient-to-r from-blue-500 to-purple-600 text-white px-8 py-3 rounded-lg font-semibold hover:from-blue-600 hover:to-purple-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="h-5 w-5 animate-spin" />
                  <span>Generating Assessment...</span>
                </>
              ) : (
                <>
                  <Zap className="h-5 w-5" />
                  <span>Generate Assessment</span>
                </>
              )}
            </button>
          </div>
        </form>
      </motion.div>
    </div>
  )
}
